package msg.project.flightmanager.exceptions;

public enum ErrorCode {
	
	EMPTY_FIELD,
	IS_NOT_OUT_OF_LETTERS,
	IS_TOO_SHORT,
	WRONG_INTERVAL,
	WRONG_FROMAT,
	IS_TOO_LONG,
	NOT_AN_EXISTING_ID_IN_THE_DB,
	OBJECT_WITH_THIS_ID_EXISTS_IN_THE_DB,
	EXISTING_TEMPLATE_LIKE_THE_GIVEN_ONE,
	EXISTING_NAME,
	EXISTING_ATTRIBUTE,
	NOT_AN_EXISTING_NAME_IN_THE_DB,
	UNEXISTING_TEMPLATE,
	NOT_AN_EXISTING_AIRPORT,
	NOT_AN_EXISTING_PLANE,
	NOT_AN_EXISTING_FLIGHT,
	DOES_NOT_HAVE_PERMISSION,
	WRONG_PASSWORD,
	EXPIRED,
	NOT_A_TOKEN_IN_THE_DB,
	NOT_AN_EXISTING_ADDRESS_IN_THE_DB,
	NOT_AN_EXISTING_COMPANY
}
