package enums;

public enum PermissionEnum {
	PERSONAL_DATA_EDIT, // CREW, FLIGHT_MANAGER, COMPANY_MANAGER, ADMINISTRATOR

	CREW_DEACTIVATE, CREW_CREATE, FLIGHT_MANAGER_DEACTIVATE, FLIGHT_MANAGER_CREATE, // COMPANY_MANAGER, ADMINISTRATOR

	AIRPLANE_EDIT, AIRPLANE_REMOVE, AIRPLANE_CREATE, // COMPANY_MANAGER, ADMINISTRATOR

	FLIGHT_EDIT, FLIGHT_CANCEL, FLIGHT_CREATE, // FLIGHT_MANAGER, ADMINISTRATOR

	FLIGHT_HISTORY_CREATE, // FLIGHT_MANAGER, COMPANY_MANAGER, ADMINISTRATOR

	FLIGHT_TEMPLATE_EDIT, FLIGHT_TEMPLATE_REMOVE, FLIGHT_TEMPLATE_CREATE, // FLIGHT_MANAGER, ADMINISTRATOR

	ITINERARY_EDIT, ITINERARY_REMOVE, ITINERARY_CREATE, // COMPANY_MANAGER, ADMINISTRATOR

	ADD_CREW_TO_COMPANY, REMOVE_CREW_FROM_COMPANY, // COMPANY_MANAGER, ADMINISTRATOR

	COMPANY_EDIT, COMPANY_REMOVE, COMPANY_CREATE, // COMPANY_MANAGER, ADMINISTRATOR

	ADD_MANAGER_TO_COMPANY, REMOVE_MANAGER_FROM_COMPANY, // COMPANY_MANAGER, ADMINISTRATOR

	AIRPORT_EDIT, AIRPORT_CREATE, // COMPANY_MANAGER, ADMINISTRATOR

	GENERATE_REPORT, // COMPANY_MANAGER, ADMINISTRATOR

	EXPORT_DATA, IMPORT_DATA, // ADMINISTRATOR

}
